Repository internetee/registry, pull requests merged in 2020-09, with the labels that each got.

#1451 Improve legal documents
  app/models/contact.rb
  app/models/domain.rb
  app/models/legal_document.rb
  config/routes.rb
  db/migrate/20191219112434_change_legal_documents_path_to_not_null.rb
  db/migrate/20191219124429_change_legal_documents_document_type_to_not_null.rb
  db/structure.sql
  test/fixtures/legal_documents.yml
  test/integration/epp/domain/delete/base_test.rb
  test/integration/epp/domain/transfer/request_test.rb
  test/jobs/domain_update_confirm_job_test.rb
  test/models/legal_document_test.rb
Labels: refactor

#1445 Remove redundant database column `domains.registered_at`
  app/models/domain.rb
  app/models/epp/domain.rb
  app/models/whois_record.rb
  app/views/admin/domains/partials/_general.html.erb
  app/views/registrant/domains/partials/_general.html.erb
  config/locales/en.yml
  db/migrate/20191217013225_remove_domains_registered_at.rb
  db/structure.sql
  test/fixtures/domains.yml
  test/models/domain_test.rb
  test/system/registrant_area/domains/details_test.rb
Labels: refactor

#1671 Send each registrar's monthly summary to Directo separately
  Gemfile.lock
  app/jobs/directo_invoice_forward_job.rb
  test/jobs/directo_invoice_forward_job_test.rb
Labels: refactor

#1662 CRL Update decoupiling
  app/models/certificate.rb
  config/application.yml.sample
Labels: refactor

#1679 Always generate reference number of length 7
  app/models/bank_transaction.rb
  app/models/billing/reference_no.rb
  app/models/billing/reference_no/base.rb
Labels: enhancement

#980 Return version logging to `prices` DB table
  app/models/billing/price.rb
  app/models/version/billing/price_version.rb
  db/migrate/20200910102028_create_version_for_prices.rb
  db/structure.sql
Labels: refactor

#1684 Reference newer version of e_invoice
  Gemfile
  Gemfile.lock
Labels: enhancement

#1686 Reference newest version of e_invoice gem
  Gemfile
  Gemfile.lock
Labels: enhancement

#1146 Refactor contact archivation
  app/models/concerns/contact/archivable.rb
  app/models/contact.rb
  app/models/inactive_contacts.rb
  app/models/version/domain_version.rb
  config/application.yml.sample
  config/locales/en.yml
  config/schedule.rb
  db/migrate/20200902131603_change_log_domains_children_type_to_jsonb.rb
  db/structure.sql
  lib/tasks/contacts/archive.rake
  test/mailers/previews/contact_mailer_preview.rb
  test/models/contact/archivable_test.rb
  test/models/contact_test.rb
  test/models/inactive_contacts_test.rb
  test/models/version/domain_version_test.rb
  test/tasks/contacts/archive_test.rb
  test/test_helper.rb
Labels: production data migration
