Repository internetee/registry, pull requests merged in 2021-01, with the labels that each got.

#1783 Registrant API: Add registrant ident to simplified domains list
  lib/serializers/registrant_api/domain.rb
Labels: enhancement

#1786 Fix automatic status handling / exposed contact attributes
  app/models/domain.rb
  app/models/epp/domain.rb
Labels: bug

#1806 Fix legal document assigning
  app/models/epp/domain.rb
Labels: bug

#1807 Registrant API: Optimize contact link(s) query
  app/controllers/api/v1/registrant/contacts_controller.rb
  app/models/contact.rb
  test/integration/api/registrant/registrant_api_contacts_test.rb
Labels: enhancement

#1823 Update Figaro version to 1.2.0
  Gemfile
  Gemfile.lock
Labels: dependencies

#1824 added test for registrar account activities
  test/system/registrar_area/account_activities_test.rb
Labels: enhancement
