Repository internetee/registry, pull requests merged in 2021-09, with the labels that each got.

#2151 Fixes for ransack gem
  app/controllers/admin/account_activities_controller.rb
  app/controllers/admin/accounts_controller.rb
  app/controllers/admin/admin_users_controller.rb
  app/controllers/admin/api_users_controller.rb
  app/controllers/admin/bank_statements_controller.rb
  app/controllers/admin/billing/prices_controller.rb
  app/controllers/admin/blocked_domains_controller.rb
  app/controllers/admin/bounced_mail_addresses_controller.rb
  app/controllers/admin/contact_versions_controller.rb
  app/controllers/admin/contacts_controller.rb
  app/controllers/admin/dns/zones_controller.rb
  app/controllers/admin/domain_versions_controller.rb
  app/controllers/admin/domains_controller.rb
  app/controllers/admin/invoices_controller.rb
  app/controllers/admin/repp_logs_controller.rb
  app/controllers/admin/reserved_domains_controller.rb
  app/controllers/registrar/account_activities_controller.rb
  app/controllers/registrar/contacts_controller.rb
  app/controllers/registrar/domains_controller.rb
  app/controllers/registrar/invoices_controller.rb
  app/views/admin/domains/index.html.erb
  app/views/registrar/domains/index.html.erb
Labels: dependencies

#2162 if new status enabled then set objupdateProhibited in locking domain
  app/models/concerns/domain/registry_lockable.rb
Labels: enhancement

#2168 Registrant url fix in email templates
  app/views/mailers/domain_expire_mailer/expired.html.erb
  app/views/mailers/domain_expire_mailer/expired.text.erb
  app/views/mailers/domain_expire_mailer/expired_soft.html.erb
  app/views/mailers/domain_expire_mailer/expired_soft.text.erb
Labels: bug
