Repository internetee/registry, pull requests merged in 2021-02, with the labels that each got.

#1805 1804 upgrade UI tests for admin portal users
  app/views/admin/repp_logs/show.haml
  config/locales/admin/repp_logs.en.yml
  test/application_system_test_case.rb
  test/integration/admin_area/account_activities_test.rb
  test/integration/admin_area/admin_users_test.rb
  test/integration/admin_area/blocked_domains_test.rb
  test/integration/admin_area/certificates_test.rb
  test/integration/admin_area/epp_logs_test.rb
  test/integration/admin_area/invoices_test.rb
  test/integration/admin_area/pending_delete_test.rb
  test/integration/admin_area/pending_update_test.rb
  test/integration/admin_area/registrars_test.rb
  test/integration/admin_area/repp_logs_test.rb
  test/integration/admin_area/reserved_domains_test.rb
  test/integration/admin_area/white_ips_test.rb
  test/integration/api/v1/registrant/contacts/list_test.rb
  test/integration/api/v1/registrant/contacts/update_test.rb
  test/models/domain_test.rb
  test/system/admin_area/bank_statement_test.rb
  test/system/admin_area/contacts_test.rb
  test/system/admin_area/domains/legal_doc_test.rb
  test/system/admin_area/invoices_test.rb
  test/system/admin_area/protected_area_test.rb
Labels: Tests prepared

#1820 Tech contacts bulk change blocked if domain UpdateProhibited
  app/models/concerns/domain/bulk_updatable.rb
  app/models/domain.rb
  app/models/tech_domain_contact.rb
  test/integration/api/domain_contacts_test.rb
Labels: bug

#1842 RWHOIS Bridge: Create separate key for Bounces API
  app/controllers/api/v1/base_controller.rb
  app/controllers/api/v1/bounces_controller.rb
  config/application.yml.sample
  test/integration/api/v1/bounces/create_test.rb
  test/integration/api/v1/contact_requests_test.rb
Labels: enhancement

#1854 Optimize WHOIS record destroy SQL check
  app/models/whois_record.rb
Labels: enhancement

#1865 Registrant User: Fix eIDAS UUID ident parsing
  app/models/registrant_user.rb
Labels: bug

#1866 Registrant API: Fix company domain query
  app/models/domain.rb
Labels: bug

#1867 Registrant API: Allow tech domain query without tech flag
  app/controllers/api/v1/registrant/domains_controller.rb
Labels: bug
